"""Pydantic v2 schemas for API v1 request and response models."""

from src.api.v1.schemas.common import ApiResponse, ErrorResponse, HealthResponse
from src.api.v1.schemas.crawler import CrawlPageResult, CrawlRequest, CrawlResponse
from src.api.v1.schemas.ingestion import (
    CheckHashesRequest,
    CheckHashesResponse,
    ChunkPreviewItem,
    ChunkPreviewRequest,
    ChunkPreviewResponse,
    EmbedTextRequest,
    EmbedTextResponse,
    IndexInitRequest,
    IndexInitResponse,
    IndexStatusResponse,
    IngestBatchRequest,
    IngestBatchResponse,
    IngestFileRequest,
    IngestFileResponse,
    ReconcileRequest,
    ReconcileResponse,
    SearchResultItem,
    SearchTestRequest,
    SearchTestResponse,
)

__all__ = [
    "ApiResponse",
    "ErrorResponse",
    "HealthResponse",
    "CrawlRequest",
    "CrawlResponse",
    "CrawlPageResult",
    "ChunkPreviewRequest",
    "ChunkPreviewResponse",
    "ChunkPreviewItem",
    "EmbedTextRequest",
    "EmbedTextResponse",
    "IndexStatusResponse",
    "IndexInitRequest",
    "IndexInitResponse",
    "IngestFileRequest",
    "IngestFileResponse",
    "IngestBatchRequest",
    "IngestBatchResponse",
    "CheckHashesRequest",
    "CheckHashesResponse",
    "ReconcileRequest",
    "ReconcileResponse",
    "SearchTestRequest",
    "SearchTestResponse",
    "SearchResultItem",
]
