"""Pydantic v2 schemas for API v1 request and response models."""

from src.api.v1.schemas.common import ApiResponse, ErrorResponse, HealthResponse
from src.api.v1.schemas.crawler import CrawlPageResult, CrawlRequest, CrawlResponse
from src.api.v1.schemas.ingestion import (
    CheckHashesRequest,
    CheckHashesResponse,
    ChunkPreviewItem,
    ChunkPreviewRequest,
    ChunkPreviewResponse,
    EmbedTextRequest,
    EmbedTextResponse,
    IndexInitRequest,
    IndexInitResponse,
    IndexStatusResponse,
    IngestBatchRequest,
    IngestBatchResponse,
    IngestFileRequest,
    IngestFileResponse,
    ReconcileRequest,
    ReconcileResponse,
    SearchResultItem,
    SearchTestRequest,
    SearchTestResponse,
)

from src.api.v1.schemas.retrieval import (
    ExplainApiResponse,
    ExplainScoringItem,
    FilterCriteriaModel,
    RetrievalHealthResponse,
    RetrievedChunkModel,
    SearchApiRequest,
    SearchApiResponse,
)

from src.api.v1.schemas.generation import (
    CartItemModel,
    CitationModel,
    GenerateApiRequest,
    GenerateApiResponse,
    GenerationConfigModel,
    ShopperContextModel,
    TokenUsageModel,
)

__all__ = [
    "ApiResponse",
    "ErrorResponse",
    "HealthResponse",
    "CrawlRequest",
    "CrawlResponse",
    "CrawlPageResult",
    "ChunkPreviewRequest",
    "ChunkPreviewResponse",
    "ChunkPreviewItem",
    "EmbedTextRequest",
    "EmbedTextResponse",
    "IndexStatusResponse",
    "IndexInitRequest",
    "IndexInitResponse",
    "IngestFileRequest",
    "IngestFileResponse",
    "IngestBatchRequest",
    "IngestBatchResponse",
    "CheckHashesRequest",
    "CheckHashesResponse",
    "ReconcileRequest",
    "ReconcileResponse",
    "SearchTestRequest",
    "SearchTestResponse",
    "SearchResultItem",
    "FilterCriteriaModel",
    "SearchApiRequest",
    "SearchApiResponse",
    "RetrievedChunkModel",
    "ExplainApiResponse",
    "ExplainScoringItem",
    "RetrievalHealthResponse",
    "CartItemModel",
    "CitationModel",
    "GenerateApiRequest",
    "GenerateApiResponse",
    "GenerationConfigModel",
    "ShopperContextModel",
    "TokenUsageModel",
]

